# Generated by Django 3.2.25 on 2025-02-11 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('topic_choices', models.CharField(choices=[('registration', 'Register / Sign Up'), ('order', 'Order Inquiry'), ('products', 'About the Products'), ('sustainability', 'Sustainability & Sourcing'), ('other', 'Other')], default='other', max_length=50, verbose_name='What is your question about?')),
                ('referral_source', models.CharField(choices=[('social_media', 'Social Media'), ('friend_family', 'Friend or Family'), ('market', 'Local Market or Shop'), ('website', 'Our Website'), ('other', 'Other')], default='other', max_length=50, verbose_name='How did you hear about Hooked on Fish?')),
                ('message', models.TextField()),
                ('read', models.BooleanField(default=False)),
            ],
        ),
    ]
