# Generated by Django 3.2.25 on 2025-02-19 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_grounds'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='profile_image',
            new_name='about_image',
        ),
        migrations.RenameField(
            model_name='grounds',
            old_name='profile_image',
            new_name='grounds_image',
        ),
    ]
