# Generated by Django 3.2.25 on 2025-02-19 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_auto_20250219_1615'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='about_image',
            new_name='profile_image',
        ),
        migrations.RenameField(
            model_name='grounds',
            old_name='grounds_image',
            new_name='profile_image',
        ),
    ]
