# Generated by Django 3.2.25 on 2025-01-30 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='caught_in_these_waters',
            field=models.CharField(default='Derryinver Bay', max_length=254),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
